---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
controllers:
  chat:
    containers:
      app:
        image:
          repository: ghcr.io/cinnyapp/cinny
          tag: v4.10.0
global:
  fullnameOverride: cinny
# ingress:
#   app:
#     className: nginx
#     hosts:
#       - host: chat.cjf.sh
#         paths:
#           - path: /
#             service:
#               identifier: app
#               port: http
#     tls:
#       - hosts:
#           - chat.cjf.sh
service:
  app:
    controller: chat
    ports:
      http:
        port: 80
    type: LoadBalancer
