---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yml
  - ./cert-manager.yml
  - ./ingress-nginx.yml
  - ./metallb.yml
  - ./node-feature-discovery.yml
  - ./prometheus.yml
