---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - repo.yml
  - release.yml
  - redis.yml
  - servicemonitor.yml
configMapGenerator:
  - name: blocky-config-values
    namespace: flux-system
    files:
      - values.yaml=values-config.yml
configurations:
  - kustomizeconfig.yml
