---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - repo.yml
  - release.yml
  - redis.yml
  - kustomizeconfig.yml
  - values-config.yml
  - servicemonitor.yml
