---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
global:
  fullnameOverride: tududi

controllers:
  tududi:
    type: statefulset
    containers:
      app:
        image:
          repository: docker.io/chrisvel/tududi
          tag: "0.86"
        env:
          TUDUDI_USER_EMAIL:
            secretKeyRef:
              name: coredns-omada
              key: username
          TUDUDI_USER_PASSWORD:
            secretKeyRef:
              name: coredns-omada
              key: username
          TUDUDI_SESSION_SECRET:
            secretKeyRef:
              name: coredns-omada
              key: username

service:
  app:
    controller: tududi
    ports:
      http:
        port: 3002

ingress:
  app:
    enabled: true
    className: nginx
    hosts:
      - host: tududi.cjf.sh
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - tududi.cjf.sh

persistence:
  db:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /app/backend/db
        readOnly: false
  uploads:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /app/backend/uploads
        readOnly: false
