---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - kube-prometheus-stack
  - blackbox-exporter
  - grafana
  - loki
  - k8s-monitoring
  - smartctl-exporter
  # - mimir-distributed
