---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/ingress-nginx
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
  dependsOn:
    - name: metallb-pool
  patches:
    - target:
        kind: HelmRelease
        name: ingress-nginx
      patch: |
        - op: add
          path: /spec
          value:
            controller:
              extraArgs:
                default-ssl-certificate: cert-manager/cjf-sh-tls
