---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: acme@cjf.sh
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "cjf.sh"
        dns01:
          route53:
            region: us-east-1
            accessKeyIDSecretRef:
              name: prod-route53-credentials
              key: access-key-id
            secretAccessKeySecretRef:
              name: prod-route53-credentials
              key: secret-access-key
