---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
fullnameOverride: ingress-nginx
controller:
  metrics:
    enabled: true
  ingressClassResource:
    default: true
  extraArgs:
    default-ssl-certificate: cert-manager/cjf-sh-tls
