apiVersion: v1
kind: Secret
metadata:
  name: esphome
  namespace: hass
data:
  secrets.yaml: ENC[AES256_GCM,data:bMIBEujp4RNCIVYxKzIZWF+HxRTM9gFRTeWEgJO/eedyDWnE3cvYPt8oKfd+7azhV5FRFaAkWMfjaBZRFqqAcjNfpR3khDkj9mrr/g0lzt9gBbtyQF1WaukwgrFW996DR/oI2H3VOZ8wR6d9E6JksjpN20i7Mw+Eb3ZGKuutCdJEJlCb987QuCvnqJs=,iv:Oh1I0Rwojaeh22K3YV8/ypXvOeie9fdbWd22sGJt1ZE=,tag:DksaXiGHUcEgvWyCWitsCQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbjZ6MThOS1AwdnVFanhh
        ang0dHVMWFFGaVNBVGk4a0tjckc1bG5wdndNClhMNkRmUVpHRnFrMVN5ckNOWXYx
        Mlk5d2d2MGk4QkRkWFBKOEZKbW9rM00KLS0tIDFwQ3pzcjEvUFEyYVRoeCs5RSth
        dmloZk9zWGMwam9BRzlSRkVONWJQQzAKXVmoK0GKgIco4tLSMn6Jumds1sqTXOsi
        d/BAbEPUaoYw40p651jok9fZucXXIZ3cxwkua0rANdvBGhDib+P+sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:37:46Z"
  mac: ENC[AES256_GCM,data:3z+kMG3RWPyo67vrLs4YAuqFBjmI/yNgboAjIWgTGRpyH49kDT2zgf0xvHHAs++ENgqJNY1BP++1JCmnYoNVOxQy0FHgCwnM2Pgp54+z/74Di1Yb+aUFyMU7K2kXfQHyj+Z3ODC/CvZlQBPd8narf18UU3yb+SgsOKsJLEN7Ovc=,iv:dcgH1bifjFXmqPcl63uyrytT/n3SBI7YvnNqFxsW7hY=,tag:8vdZMpcRuUX9Ha7oPX1OCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
