apiVersion: v1
kind: Secret
metadata:
  name: esphome
  namespace: hass
stringData:
  wifi_ssid: ENC[AES256_GCM,data:KqV+,iv:OxjMoM0Rih1Isrpl0HoeR0sL4zSiNIvpAzLbWomHg7Q=,tag:V8Mj2+WFwSAqCwdey7c5ow==,type:str]
  wifi_password: ENC[AES256_GCM,data:bT+DZTOO9bg/Xk4uRkZdxQ==,iv:vbS3nooqGbmsD1QUPk81iRksAIxuw+i13/RNIqsneT8=,tag:yuE6gGuq3j2OpMJoQ4IYhQ==,type:str]
  ota_password: ENC[AES256_GCM,data:ZXuTwtKN55kM5pP2Zq8=,iv:kOR9lNeG8xTnQlMnsv8hpl1EWLRY+Cy8NtdpyDscUn4=,tag:Eu5nBGALWEy3SChExyt+YQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSmpqUjJvUWZEQ1hjRUc5
        TE02a2tKbHhHTjgwc2dMNG9ieGJpQ0E3UjM4CjdyNmVMd1lsUkFucHdWYVY3d1BQ
        THZtL1lIZ3QwdXIwK1N4QjhWS2M0NTAKLS0tIG0xZERqTnk0TGg3WHBqOXQxQzhU
        MHcwYys4a0NrbEt1RzZRMnB5KzlZTjgKX3/Msc9SdpXfgi0I2V9FvHZAqA6OvNmR
        0Y5dVupIKL2RfhiAg6mk+Pxze35XoQQUt92z6Sabliv6mP/N8lWcfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:28:44Z"
  mac: ENC[AES256_GCM,data:1mQVhxOA03yNbfGIEuxEio+hCTj1mGRB8V4tP65fCEV9d876ki7hL9m6mzORRyqW7w0I95q6s+Xpvw/L0Hqk9AmY4KrfYseAPJ5RxwDJ+CIYQP1hZXgryQedWDfRZMadIQEEcFMbEeLWvMUX3si6a6alkdoLRnrtWcCXnlt4KAc=,iv:pMQ6ft3tMg75mD8C+MKNuiMGVBP/cvxTyYesjeVGwCI=,tag:Sv/37KjR2zGMoDP+IDzxyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
