apiVersion: v1
kind: Secret
metadata:
  name: esphome
  namespace: hass
stringData:
  secrets.yaml: ENC[AES256_GCM,data:h1DJZ1ZzhBaiROSTnTvQiQmLu/tXgPfXbdTuHUQN9qax69cu23xrILLYyhmvWWb+Mb+/QBbO/6IouHgeSoh8teziXv/dM802veCA07OJODf9UjwB6dzWQYXNC7ZGEyjzWJDSY+hncfJpFYZQ9ZFfN87h9U2rlxxssdYDrdNHyq3QnC2eruFq0m85wFKI5bjDFBF8riRzWSKIIDInHFNX5Y9r6M3UB91ifnAhIOEeig6/34dHDP/wA0qTnoQTJg9h9k+x57LQVpWjCjjZA537Jyo=,iv:KWE6BRiqw4TTgrUYBnF8vL5XKUbc+Dq6HC9hw4ifgi4=,tag:iqfZ2PbhRmX7BDuhKWDtJg==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVmc5RXN2V2FtSXRYcnFh
        d05XeERPYzBvMWxBcHVnaGRlQmQwSlRROWtjCit5eEs3djZqdnBVdVQ2dG5FZ2NW
        M2MrNEt3cmNZQUhZRUpYUTczSFZrTWsKLS0tIDBPa0pQWXVJU2ZpRlQ4RWNBNldC
        SkZwN25PV1A0NzcvTUY5SlNPU3ltcWMKOeNvU4dBmz3gU1v3SO4wCZ/sSPUZLXN/
        BlGDYtPtp4cMcWpvtuw9qvoIcxO30n85szl3E7sNDngGk5mej2Mx0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T22:31:02Z"
  mac: ENC[AES256_GCM,data:YUSI30hh4xJuya1Kbizr3P69EVTzK1ZvVDH/Jf3zOd3KCU4LC5NRnu6oJxVkGRzeBkocle00EtaFnvu7KIWOPJPObilp1vI/k5mhNUiPmg1XHj9gHQbCmGPI2gt7AOlDoX3Duq4vytm9nBpKS50dIf8lHZONFtvtuL1UQyBV1R0=,iv:T9xPHiT1oMDh1a8SOoWq+tQOpR2THzyPZtiLyKkWMFI=,tag:1Ktay9hZXEQV3erafr2+ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
