apiVersion: v1
kind: Secret
metadata:
  name: esphome
  namespace: hass
data:
  secrets.yaml: ENC[AES256_GCM,data:J6TfCsvyMDCKc+Fihf6rc/tTPub6Ycm57Bg5X11HOZR+H/Aff2evShabAEIUSDmRtgQgGYRBU+5Rqjce32DpgsAC8vDs1peb/9z437B5mLDduf86pteL9Q12uKR02MFcIWh+UfGDipqF+SVyyjruw0e4fUDnCrLa8jQrLokyy5LHLtWawOFrNPLQVe+R73CDm+wR88enHipP78nXEJX7nNTwpU2D4hC1Ahp4t5TGAg==,iv:OGRwQMEzt7+Hur64zM2awaqy/lYPH0KY92wsFh6vR9g=,tag:RXC4KGHd3g0tWBihTJKrjQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM2pWemR1U0Q4OVdsN3dq
        N29aemQ2QndhaDYveUhzNVE2UUJyVmpzc3c4CmFtd2VtbUlIYUhzWkVtV2t6MFZD
        YUYvYTN5TW5LUnhTUlVpV1RFb1pQNkUKLS0tIGhsWGlXbUx5UmJiRmhKdGZnMmpH
        ZGE3eVIxa1QwT3h3bWhVQVN0MzlDWk0K23s39FQU8wT9VmxR9HoRU8fxjIcJDrHk
        gvVc+HfFwFjOCGeEnNYw8XQHlY9mZmdtoxdRgB9O9go9qDxqC491xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T18:49:34Z"
  mac: ENC[AES256_GCM,data:aaJe2cH1c2grFDQIII8MXI+QmZqIpepA/+0LroOS5Tbl2JXfszq7BNMLyOy7MURD2l4MlF2s3ZdlgWNffzya1aTgyijDcEvKJemk3a9WJ0nVW2cbDSod7NLWV3v3CFcnHofozHdpFedU2tKFvseugL8WNhD7fCCKHuTJFw+YROU=,iv:MB2dg/fJgOZLufh96csNs3rWlSwfXfc+8DfxiJNQ4cY=,tag:9Eshwt5LEoB2wh3YygihHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
