apiVersion: v1
kind: Secret
metadata:
  name: esphome
  namespace: hass
stringData:
  wifi_ssid: ENC[AES256_GCM,data:Jy1q,iv:pHq4Em06yiwUFzF5EESp8xJQSGXy1CqRg2hKbQxRTUI=,tag:uBMTeT2m8jwCe6sS4WD+uQ==,type:str]
  wifi_password: ENC[AES256_GCM,data:U9npL3VsznXx1zFBM5m9Bw==,iv:v4tUHbZ0b9mZTRlPM9Ps5hR3cPMXYFURhfGSNm/BloA=,tag:8Reb90FevjAsmQVO36205w==,type:str]
  ota_password: ENC[AES256_GCM,data:pDBRMDwbpYRbKMC8cZg=,iv:y/Lk/W5PEn2dx2SxRsQzMvD+gpuGSMKxUxgIXa1MzWc=,tag:ZqWtgSipGJWwm2dbVyZdew==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTjdhTVAwWXhPNWhHdU9C
        djVwVTNSaytLVkVQSythTkIxUUl6NkUyZFdJCjR0aGhVS1liWm8ySFBuOGhkZE1H
        MDZDNlpuS2dxOUVRUFZmRUhadUk1Y0kKLS0tIGF2QnJVOHdHbDRhdVF2WG1IaEZr
        OUJ6NS9PalBuYUNIZTVkT0FYTFlMcXcKzJdqfh47sPSvALd9lTzuLXk81X21ogPk
        7nYytlbHVypjHQt2JpYPTeEPPf+JAiZcR0CvZ5c3sM6nu76mKoTxdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-06T00:32:26Z"
  mac: ENC[AES256_GCM,data:lcMrNXrJhMTJqV9hk+1JKawP1JC806ziTt3VYh1hzvL3CUr1XY/6PVALArf1i7S2oXoh69CKssA+lx3So2ASY8U9MZ15jMaH5EcTa/WxAih8L9M8mpoE3j9WL6imX56EVpFFmavY/OKOZ+NGFtp4luMClFT4UiRtuUzDio9YfJM=,iv:yA7LTey4cHZy1WcU3zuQH6eu/hzG6TwqwbR8PtR8Xuk=,tag:XKMCQ0QaSXy7puZVb9YfHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
