resources:
  - bjw-s.yml
  - cloudnative-pg.yml
  - external-secrets.yml
  - grafana.yml
  - immich.yml
  - ingress-nginx.yml
  - jetstack.yml
  - metallb.yml
  - node-feature-discovery.yml
  - openebs.yml
  - prometheus-community.yml
  - tailscale.yml
  - valkey.yml
