---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - db
  - piper
  - wakeword
  - whisper
  - mqtt
  # - zigbee2mqtt
  # - hass
  # - esphome
