---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yml
  - release.yml
  - secrets.sops.yml
  - scrapeconfig.yml
configMapGenerator:
  - name: hass-config-values
    namespace: flux-system
    files:
      - values.yaml=values-config.yml
configurations:
  - kustomizeconfig.yml
