---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
global:
  fullnameOverride: hass
controllers:
  hass:
    type: statefulset
    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name":"multus-dmz",
              "namespace": "kube-system",
              "ips": ["10.0.4.240/24"]
            },
            {
              "name":"multus-iot",
              "namespace": "kube-system",
              "ips": ["10.0.5.240/24"]
            }
          ]
    containers:
      app:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: "2025.10"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BROADCAST
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  app:
    controller: hass
    ports:
      http:
        port: 8123

ingress:
  app: &ingress
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: hass.cjf.sh
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - hass.cjf.sh

persistence:
  config:
    existingClaim: "{{ .Release.Name }}"
    globalMounts:
      - path: /config

  backups:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config/backups

  # config-file:
  #   name: hass
  #   type: configMap
  #   advancedMounts:
  #     hass:
  #       app:
  #         - path: /config/configuration.yaml
  #           subPath: configuration.yaml
  #
  # automation-manual:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/automations/manual
  #
  # automation-ui:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/automations/ui
  #
  # script:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/script
  #
  # scene-manual:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/scenes/manual
  #
  # scene-ui:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/scenes/ui
  #
  # sensor:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/sensors
  #
  # template:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/templates
  #
  # schedule:
  #   <<: *v
  #   globalMounts:
  #     - path: /config/schedules

  # db:
  #   name: hass-db
  #   type: secret
  #   advancedMounts:
  #     hass:
  #       app:
  #         - path: /config/db.yml
  #           subPath: db_url
# configMaps:
#   config:
#     data:
#       configuration.yaml: |
#         default_config:
#         ffmpeg:
#
#         prometheus:
#           namespace: hass
#
#         http:
#           use_x_forwarded_for: true
#           trusted_proxies:
#             - 0.0.0.0/0
#
#         automation manual: !include_dir_list automations/manual
#         automation ui: !include_dir_list automations/ui
#         script: !include_dir_list scripts/
#         scene manual: !include_dir_list scenes/manual
#         scene ui: !include_dir_merge_list scenes/ui
#         sensor: !include_dir_merge_list sensors/
#         template: !include_dir_merge_list templates/
#         schedule: !include_dir_merge_named schedules/
