---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
global:
  fullnameOverride: hass
controllers:
  hass:
    type: statefulset
    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name":"multus-iot",
              "namespace": "kube-system"
            },
            {
              "name":"multus-dmz",
              "namespace": "kube-system"
            }
          ]
    containers:
      app:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2025.10
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BROADCAST

service:
  app:
    controller: hass
    ports:
      http:
        port: 8123

ingress:
  app: &ingress
    className: nginx
    hosts:
      - host: hass.cjf.sh
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - hass.cjf.sh

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  backups:
    type: persistentVolumeClaim
    storageClass: zfs-dataset
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config/backups

  config-file:
    name: hass
    type: configMap
    advancedMounts:
      hass:
        app:
          - path: /config/configuration.yaml
            subPath: configuration.yaml

configMaps:
  config:
    data:
      configuration.yaml: |
        default_config:
        ffmpeg:

        prometheus:
          namespace: hass

        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 0.0.0.0/0

        automation manual: !include_dir_list automations/manual
        automation ui: !include automations/ui
        script: !include scripts/
        scene manual: !include scenes/manual
        scene ui: !include_dir_merge_list scenes/ui
        sensor: !include_dir_merge_list sensors/
        template: !include_dir_merge_list templates/
        schedule: !include_dir_merge_named schedules/
