---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: esphome
  namespace: monitoring
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - epl-kitchen.cjf.lan:6053
        - epl-office.cjf.lan:6053
        - epl-paige-office.cjf.lan:6053
        - epl-stairs.cjf.lan:6053
        - esp-bedjet.cjf.lan:6053
        - esp-office.cjf.lan:6053
