---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ingress
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    ingress:
      selector: {}
