---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - secrets.sops.yml
  - release.yml
configMapGenerator:
  - name: frigate-config
    namespace: flux-system
    files:
      - config.yml=values-config.yml
configurations:
  - kustomizeconfig.yml
