---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - secrets.sops.yml
  - db.yml
  - volume.yml
  - mattermost.yml
configMapGenerator:
  - name: mattermost-config-values
    namespace: flux-system
    files:
      - values.yaml=values-config.yml
configurations:
  - kustomizeconfig.yml
