apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
stringData:
  client_id: ENC[AES256_GCM,data:OVNRFJV3qLur2uMelw2pY8amIur66ZdIGY58wxRt5PsU49Z9,iv:CPVgGsx8wK0pMdttgwVqOnlk5jZEtrmvHLz8RvYe4g8=,tag:DuFMDqG8dTQSIuups1omBw==,type:str]
  client_secret: ENC[AES256_GCM,data:kGd1yP+ruL5ZOEqwdMmqp+qJP1XfhVGTwT8cdgNgFog=,iv:h4zu3hGhmomEZSObkn+QkRRAN85wemsk0I8YVCcn07c=,tag:OhQCqakVM2ZZWJUBLxQbHA==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdEMveTk3enFldmNNL2xB
        aUdPWldvNGVLTTNENlk4QzFmUStwNUk1d1ZBCmdqZW9LWE1FZlBLZ215blhHdnVh
        aWlJNXJpRTRpRGRUaDBQaG40cjB1d2cKLS0tIEQ5QTE3ODFOM2dGcVpSdVVtcjlp
        KzRleWJ2dUZ2N3NSUHNFZzIya0poenMKUftJ4NK4cZ2OyAuYc/01CX3qxIHF75GX
        fVWs/y3K3wlSi2Ic7inOFjdrr9m3jTVu3wxdSOz9TTBp0FMreHBMrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T15:20:42Z"
  mac: ENC[AES256_GCM,data:u4zKkukCfWH7czElzarcLQpVhVKFequwXb3h7KHfDVFvp047RLsWOhHc03yMRgXxbUwwTWidLDy1sn7rKnjd12wo+q4wgIWa5kOlPu7TS2IwU/JPAnvzAUjMYqT62AHxDblHgLFwNc+36cGYcVJkQ/w4wqfcdv2jSZw9v1v80E4=,iv:m4lpn6wb/zJT3SPs4tSeqD7L+pfbEq5vaRvDo+aiS7s=,tag:F2K6KpGBJaVp+1t8XPVN0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
