---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
  - repo.yml
  - secrets.sops.yml
  - db.yml
  - redis.yml
  # - release.yml
configMapGenerator:
  - name: paperless-config-values
    namespace: flux-system
    files:
      - values.yaml=values-config.yml
configurations:
  - kustomizeconfig.yml
