apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: ENC[AES256_GCM,data:pCwjpO9B9QKzo8unFR8LtKkfp+EnV59/eBr7Hjg9Se4GQdSFkSQtHN0HQwoF+AiRZmUNeDczx3roJUsffvWLYi1UYGCmBV/qnR8KB+M6LPa6zrcB7bBL1bzf1kA1zbh1DWI5ov7fjMBDltvROZCx4GhNRUYw610ivHhJiMfhyFDzjgviM1QOAq8sily7AfI8WfK8bSDSBNbfEkOjbgIetd8OnHCY2JdVO428sb3MfY/PJPGRnoDndLkf0BlKWJd3Zezw02j9EoR6Cv4CXwfbDOIvXRRx7WG9S/9NBGH5jA3CRjFtjkegEIqfQPdT2sdBiIhfzVQ6CGgt+zPyJqqJhjQs,iv:cnUWgKNheCSIvGH3n+wpITwT1t7cnBUyUWVRmTBPHZQ=,tag:wAZdBos0uqPruxyiSsnFTQ==,type:str]
sops:
  age:
    - recipient: age1rl3vtd8j4680289tkm2s7jmy25ev83gdwca5hrgprauue506gcuqktqzmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YUs5TUFwWDBWVE9WRmVL
        RWZYY291LzN2ZjBuaUthTGZXdXRsb09PdTEwClhGSmdCbGFVaTJUeGREVEl6Mmgw
        eDFENU9YVG5DYXlLVysrN1k1TFVBSFUKLS0tIDlMQkxXMTVDa1hkYkc1eHo0WHNB
        Umo2WlhLYjYrZGlUaUdXZ2FrRGFJYTgKC9/lvKiWAcEH5uvJmVBOsMmXcQpXTcc2
        waAofnqYGtXm5tEyXBUWkQbL+AgHZpLZUqlNr1vhhwzreL2vunGkrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T15:21:25Z"
  mac: ENC[AES256_GCM,data:3eWyBZ8OLaAClZkM3wFBCVdxAyD3ZuqSInrUqNIUS7A6ksGPYgKlhg1PdaVHVkoh3RI31zWnqW0Wag2aHsncG1huUecQ2cA7MgfTShUakk7pkWuqZRuc/nk0ZtYeEqnsWuo9yzxYS58LxxN2CaYsF6KgvE1/vr/2eq2h135gUD0=,iv:XJHp44HRRZph1gPHooi/oRJ8YaM+DeOJgBQT3/3Llwc=,tag:EbY+/8q4veGz9JWA/mUEvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
